/* Generated by vessels.html — do not hand-edit; the configurator
   rewrites this whole file. Place data lives in places.js.

   Anything absent falls back to DEFAULT_CUP in cup.js, which is the
   plain paper cup the site has always shown. */
const CUPS = {
  "Angelina Paris": { vessel:"Bell glass", mallow:"Pillow", count:13, finish:"solid", size:2.2, l:0.295, c:0.051, h:47 },
  "Caffè Panna": { vessel:"Paper cup", mallow:"Pillow", count:1, size:2.2, tilt:-13 },
  "Cocoa Cabin": { vessel:"Paper cup", mallow:"None", count:0, l:0.545, c:0.051, h:47 },
  "Frenchette Bakery": { vessel:"Paper cup", mallow:"None", count:0, l:0.31, c:0.051, h:47 },
  "Glace by Noglu": { vessel:"Paper cup", mallow:"Sphere", count:1, size:2.2, l:0.41, c:0.051, h:47 },
  "Glace Rockefeller Center": { vessel:"Paper cup", mallow:"Sphere", count:0, size:2.2, l:0.435, c:0.051, h:47 },
  "Gramercy Tavern": { vessel:"Mug", mallow:"Pillow", count:1, size:2.2, l:0.327, c:0.07, h:47 },
  "La Maison du Chocolat": { vessel:"Paper cup", mallow:"None", count:0, label:"patch", l:0.24, c:0.051, h:47 },
  "Mango Mango": { vessel:"Tumbler", mallow:"None", count:0, finish:"solid", label:"wrap", l:0.585, c:0.051, h:47 },
  "MarieBelle New York": { vessel:"Mug", mallow:"None", count:0, l:0.415, c:0.051, h:47 },
  "Matto Espresso": { vessel:"Paper cup", mallow:"None", count:0, l:0.61, c:0.051, h:47 },
  "Max Brenner Union Square": { vessel:"Bell glass", mallow:"None", count:0, finish:"solid", label:"patch", l:0.415, c:0.072, h:47 },
  "No Chewing Allowed": { vessel:"Paper cup", mallow:"None", count:0, l:0.47, c:0.051, h:47 },
  "Ole & Steen": { vessel:"Paper cup", mallow:"None", count:0, l:0.305, c:0.051, h:47 },
  "Rigor Hill Market": { vessel:"Paper cup", mallow:"Cylinder", count:10, size:1.75 },
  "S'mores N'more": { vessel:"Paper cup", mallow:"Pillow", count:1, size:2.2, tilt:-11, l:0.465, c:0.068, h:47 },
  "Starbucks Reserve": { vessel:"Paper cup", mallow:"None", count:0, l:0.415, c:0.06, h:47 },
  "The Cocoa Store": { vessel:"Paper cup", mallow:"None", count:0, l:0.405, c:0.051, h:47 },
  "United Chocolate Works": { vessel:"Paper cup", mallow:"Sphere", count:9, size:1.6, l:0.485, c:0.07, h:47 },
  "Venchi NoMad": { vessel:"Paper cup", mallow:"None", count:0, l:0.34, c:0.056, h:47 },
};

PLACES.forEach(p => { if (CUPS[p.place]) p.cup = CUPS[p.place]; });
